### ISSUE TITLE
An error occurred while communicating with the Tableau Data Extract data source 'Untitled Data Source'

### ISSUE THREAD

**Issue by skyth540** [innobi/pantab#334] opened 2024-09-16 20:15 UTC
**Describe the bug**
I successfully created a .hyper, but in tableau, it is unable to connect to it. Version 2023.1.0

"""
Unable to connect to the server. Check that the server is running and that you
have access privileges to the requested database.
Error Code: FAB9A2C5

[SQLSTATE:0AS01] error opening database 'test': There was an error during loading database: unsupported version. To open this database, please update your product: DatabaseId: "hyper.file:G:/Duda/Data Projects/Kroger 8451/Raw Data New/parquet/test.hyper"
Unable to connect to the Tableau Data Extract server "". Check that the server is running and that you have access privileges to the requested database.
"""

**To Reproduce**

```python
import pyarrow.parquet as pq
import pantab as pt

folder_path = r"G:\...\parquets"

table = pq.read_table(folder_path)

path = r"G:\...\test.hyper"

pt.frame_to_hyper(table, path, table = 'test')
```

**Comment by RSchaper10** [comment] 2024-09-16 21:57
I was able to replicate the issue on my machine as well (Apple M1 Pro Sonoma 14.6.1)

Unable to complete action
Unable to connect to the server. Check that the server is running and that you have access privileges to the requested database.
Error Code: FAB9A2C5
[SQLSTATE:0AS01] error opening database 'example': There was an error during loading database: unsupported version. To open this database, please update your product: DatabaseId: "hyper.file:/Users/robschaper-m1/Code/pantab/example.hyper"
Unable to connect to the Tableau Data Extract server "". Check that the server is running and that you have access privileges to the requested database.

When Attempting to open the example hyper file in Tableau Desktop (2024.2.2), generated using the following in Jupyter Notebook:

import pandas as pd
import pantab as pt

df = pd.DataFrame([
    ["dog", 4],
    ["cat", 4],
], columns=["animal", "num_of_legs"])

pt.frame_to_hyper(df, "example.hyper", table="animals")

**Comment by skyth540** [comment] 2024-09-17 13:37
A similar thing happened when opening in alteryx 2021.2

"""
error opening database 'test': There was an error during loading database "hyper.file:G:\...\test.hyper":unsupported version 4 (max supported version: 1). To open this database, please update your product. Context: 0xd6232f85

"""

**Comment by WillAyd** [comment] 2024-09-17 16:40
I think this is a duplicate of https://github.com/innobi/pantab/issues/331

**Comment by WillAyd** [comment] 2024-09-17 19:04
If you install from main you should now be able to try:

```python
params = {"default_database_version": "1"}
pt.frame_to_hyper(table, path, table = 'test', process_params=params)
```

can you see if that works to resolve the issue?

FWIW I asked about the database versions on the Tableau slack today, so hope to hear back about that soon

**Comment by WillAyd** [comment] 2024-09-18 15:48
OK Tableau shared the following with me which I think has good info:

https://tableau.github.io/hyper-db/docs/hyper-api/hyper_process/#default_database_version

Looks like version 0 is the default but 1 is deprecated. So I think we should set the default value to 2 and leave it to the user to use a more recent version? @skyth540 that wouldn't solve the issue you are seeing with alteryx by default, but as mentioned in the previous post you can now provide the `process_params` argument to override that default.

Thoughts?

**Comment by WillAyd** [comment] 2024-09-18 15:49
@jorwoods may have some input as well

**Comment by jorwoods** [comment] 2024-09-18 16:20
Given the versions of Tableau Desktop/Server/Prep supported, I think setting the hyper version to 2 as a default makes sense. I'll make a PR soon to update the pantab docs to reference that page so pantab users know the implications of updating that setting.

**Comment by skyth540** [comment] 2024-09-18 17:16
> If you install from main you should now be able to try:
> 
> ```python
> params = {"default_database_version": "1"}
> pt.frame_to_hyper(table, path, table = 'test', process_params=params)
> ```
> 
> can you see if that works to resolve the issue?
> 
> FWIW I asked about the database versions on the Tableau slack today, so hope to hear back about that soon

I ran pip install git+https://github.com/innobi/pantab.git

And got this error:
Building wheels for collected packages: pantab
  Building wheel for pantab (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pantab (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      *** scikit-build-core 0.10.6 using CMake 3.30.3 (wheel)
      *** Configuring CMake...
      2024-09-18 11:13:25,766 - scikit_build_core - WARNING - Can't find a Python library, got libdir=None, ldlibrary=None, multiarch=None, masd=None
      loading initial cache file E:\TEMP\tmpdq35650p\build\CMakeInit.txt
      -- Building for: NMake Makefiles
      CMake Error at CMakeLists.txt:2 (project):
        Running
     
         'nmake' '-?'
     
        failed with:
     
         no such file or directory


      CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!

      *** CMake configuration failed
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pantab
Failed to build pantab
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pantab)

**Comment by skyth540** [comment] 2024-09-18 17:46
I uninstalled pantab, and successfully reinstalled it using pip install git+https://github.com/innobi/pantab.git

I got this error:

----> [4](vscode-notebook-cell:?execution_count=2&line=4) pt.frame_to_hyper(table, path, table = 'test', process_params=params)

TypeError: frame_to_hyper() got an unexpected keyword argument 'process_params'

**Comment by WillAyd** [comment] 2024-09-19 18:07
@skyth540 hard to say. Might be helpful to post the full traceback and make sure the file paths are resolving to the locations you think they are

**Closed** 2024-10-02 15:49 UTC
