### ISSUE TITLE
Missing permissions to start a new Hyper instance

### ISSUE THREAD

**Issue by lazargugleta** [innobi/pantab#360] opened 2024-10-07 15:29 UTC
**Describe the bug**
By creating the hyper file and using `frame_to_hyper`, a new hyper instance fails to start.
I assume that by introducing the new process_params parameter, there was a change that disrupted new permissions on accessing the executable.
Do you know if this is a bug or intended behavior? Can the permissions be given in this process_params parameter?

**To Reproduce**
1. Make a polars dataframe
2. Create hyper file using frame_to_hyper

```python
import polars as pl
import pantab as pt

# single precision float support requires database version 4+
df = pl.DataFrame(
  {"int32": pl.Series([3], dtype=pl.Int32)}
)

pt.frame_to_hyper(
    df,
    "example.hyper",
    table="test",
    process_params={"default_database_version": "3"}
)
```
Output:
```
Traceback (most recent call last):
  File "/home/gugleta/.cache/JetBrains/RemoteDev/dist/e632f2156c14a_pycharm-professional-2024.1.4/plugins/python/helpers/pydev/pydevd.py", line 2252, in <module>
    main()
  File "/home/gugleta/.cache/JetBrains/RemoteDev/dist/e632f2156c14a_pycharm-professional-2024.1.4/plugins/python/helpers/pydev/pydevd.py", line 2234, in main
    globals = debugger.run(setup['file'], None, None, is_module)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gugleta/.cache/JetBrains/RemoteDev/dist/e632f2156c14a_pycharm-professional-2024.1.4/plugins/python/helpers/pydev/pydevd.py", line 1544, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gugleta/.cache/JetBrains/RemoteDev/dist/e632f2156c14a_pycharm-professional-2024.1.4/plugins/python/helpers/pydev/pydevd.py", line 1551, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gugleta/.cache/JetBrains/RemoteDev/dist/e632f2156c14a_pycharm-professional-2024.1.4/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/gugleta/.config/JetBrains/PyCharm2024.1/scratches/scratch.py", line 9, in <module>
    pt.frame_to_hyper(
  File "/home/gugleta/.cache/pypoetry/virtualenvs/cxbi-LF4XS2gW-py3.12/lib/python3.12/site-packages/pantab/_writer.py", line 61, in frame_to_hyper
    frames_to_hyper(
  File "/home/gugleta/.cache/pypoetry/virtualenvs/cxbi-LF4XS2gW-py3.12/lib/python3.12/site-packages/pantab/_writer.py", line 115, in frames_to_hyper
    libpantab.write_to_hyper(
RuntimeError: Failed to start a new Hyper instance.
Context: 0x86a93465
Caused by:
Could not spawn the Hyper server process /home/gugleta/.cache/pypoetry/virtualenvs/cxbi-LF4XS2gW-py3.12/lib/python3.12/site-packages/pantab/hyper/hyperd.
Hint: Make sure the Hyper executable exists and has execution permissions.
Context: 0xeee3fd70
Caused by:
execve failed: Permission denied
Context: 0x7e9110c
```

**Desktop (please complete the following information):**
 - OS: Linux (wsl on Windows)
 - Pantab: 5.1.0rc0
 - On windows it works for this simple example but for more complex ones I get this error message:
 ```
  File "C:\Users\gugleta\OneDrive\OneDrive\Tab.py", line 247, in df_to_tableau
    pantab.frame_to_hyper(df, temp_file_in.name, table="data")
  File "C:\Users\gugleta\AppData\Local\pypoetry\Cache\virtualenvs\cxbi-eIU48M8u-py3.12\Lib\site-packages\pantab\_writer.py", line 61, in frame_to_hyper
    frames_to_hyper(
  File "C:\Users\gugleta\AppData\Local\pypoetry\Cache\virtualenvs\cxbi-eIU48M8u-py3.12\Lib\site-packages\pantab\_writer.py", line 127, in frames_to_hyper
    shutil.move(str(tmp_db), database)
  File "C:\Python3_12_2_64bit\Lib\shutil.py", line 906, in move
    copy_function(src, real_dst)
  File "C:\Python3_12_2_64bit\Lib\shutil.py", line 460, in copy2
    _winapi.CopyFile2(src_, dst_, flags)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process
```

**Comment by WillAyd** [comment] 2024-10-07 15:33
Hmm that's strange. And you never had this issue prior to the release candidate right?

> I assume that by introducing the new process_params parameter, there was a change that disrupted new permissions on accessing the executable.

Shouldn't be the case!

**Comment by lazargugleta** [comment] 2024-10-07 15:42
> Hmm that's strange. And you never had this issue prior to the release candidate right?

That's correct, never before this.

**Comment by WillAyd** [comment] 2024-10-07 15:44
Can you check the permissions of the Hyper executable?

```bash
ls -l /home/gugleta/.cache/pypoetry/virtualenvs/cxbi-LF4XS2gW-py3.12/lib/python3.12/site-packages/pantab/hyper/hyperd
```

**Comment by lazargugleta** [comment] 2024-10-07 15:47
Sure!
```
-rw-r--r-- 1 gugleta gugleta 218425112 Oct  7 17:41 /home/gugleta/.cache/pypoetry/virtualenvs/cxbi-LF4XS2gW-py3.12/lib/python3.12/site-packages/pantab/hyper/hyperd
```

**Comment by WillAyd** [comment] 2024-10-07 15:49
Alright thanks. Well...therein lies the problem. It looks like that file is missing the executable permissions it needs; must be getting stripped somewhere along the way

**Comment by WillAyd** [comment] 2024-10-07 15:52
Which version of Python are you using?

**Comment by lazargugleta** [comment] 2024-10-07 15:53
Python 3.12.4

**Comment by WillAyd** [comment] 2024-10-07 16:00
Hmm thanks. Although to my comment before...it looks like pantab 5.0.0 installs with the same file permissions, so maybe its not that. I can reproduce this though, so will take a closer look.

> On windows it works for this simple example but for more complex ones I get this error message:

This is a little harder for me to reproduce as I don't have access to a windows machine. But basically the pantab writer tries to first write to a temp file before moving it to the "example.hyper" location you are asking for. The point of that is to have an atomic transaction and not corrupt any "example.hyper" that may already exist there if the write to Hyper fails.

Your Windows traceback suggests that there is a handle to "example.hyper" that prevents it from being written to again. You aren't trying to write to the file while it is open by Tableau right? Do you have any way of seeing which process is locking that?

**Comment by lazargugleta** [comment] 2024-10-07 16:23
Good that you can reproduce it.

As to regards the windows issue, this could be the case because I am using NamedTemporaryFile object.
This setup worked before so I would have to check it further.

**Comment by lazargugleta** [comment] 2024-10-08 15:39
Very interesting find.
I tried now to install the `tableauhyperapi` back but the issue persists.

**Closed** 2024-10-08 17:25 UTC

**Comment by WillAyd** [comment] 2024-10-08 18:35
Hey @lazargugleta this should be fixed in rc1, which is now on pypi. If you have any trouble let me know
