### ISSUE TITLE
pantab is incompatible with the version of Tableau Hyper API installed on your system

### ISSUE THREAD

**Issue by cmcrae13** [innobi/pantab#145] opened 2022-03-24 01:30 UTC
Unsure how to proceed...

**Pantab install**
Requirement already satisfied: pantab in /usr/local/lib/python3.7/dist-packages (2.1.0)
Requirement already satisfied: tableauhyperapi in /usr/local/lib/python3.7/dist-packages (from pantab) (0.0.14567)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from pantab) (1.3.5)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from pantab) (1.21.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->pantab) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->pantab) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->pantab) (1.15.0)
Requirement already satisfied: cffi!=1.14.3,<2,>=1.12.2 in /usr/local/lib/python3.7/dist-packages (from tableauhyperapi->pantab) (1.15.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi!=1.14.3,<2,>=1.12.2->tableauhyperapi->pantab) (2.21)

---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
[<ipython-input-4-a8d341fb4330>](https://jhvkagqxwjc-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20220322-060047-RC00_436415511#) in <module>()
----> 1 import pantab

2 frames
[/usr/local/lib/python3.7/dist-packages/pantab/__init__.py](https://jhvkagqxwjc-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20220322-060047-RC00_436415511#) in _check_compatibility(check, message)
     46 def _check_compatibility(check, message):
     47     if not check:
---> 48         raise NotImplementedError(message + "\n" + api_incompatibility_msg)
     49 
     50 

NotImplementedError: expected 'hyper_rowset_chunk_field_values' to have the signature 'struct hyper_error_t *(*)(struct hyper_rowset_chunk_t *, size_t *, size_t *, uint8_t * * *, size_t * *, int8_t * *)', got 'void(*)(struct hyper_rowset_chunk_t *, size_t *, size_t *, uint8_t * * *, size_t * *)'

pantab is incompatible with the version of Tableau Hyper API installed on your
system. Please upgrade both `tableauhyperapi` and `pantab` to the latest version.
If doing so does not fix this issue, please file an issue at
https://github.com/innobi/pantab/issues mentioning the exact pantab and HyperAPI
versions which triggered this error.

**Comment by WillAyd** [comment] 2022-03-24 01:43
Does downgrading to an older version of the hyper api work? The version you have looks to have just been released today with some ABI breaking changes. Will need a PR to support that

@vogelsgesang

**Comment by vogelsgesang** [comment] 2022-03-24 11:55
Indeed, the interface of `hyper_rowset_chunk_field_values` changed with the latest HyperAPI release. Downgrading should fix this, until a solution in pantab is available.
Good that we put a detection mechanism for that into pantab :)

**Comment by vogelsgesang** [comment] 2022-03-24 13:08
From Hyper's internal git log:

```
The commit [i.e., the change which broke this] also removes the redundant nullValues array from the hyper_rowset_chunk_field_values interface. The values are now simply nullptrs if they are null. Also, the hyper_rowset_chunk_field_values interface is now noexcept since it no longer allocates any memory.
```

So the check [here](https://github.com/innobi/pantab/blob/99153cbef2518967a568e2d7a4bb8be5759ce481/pantab/src/reader.c#L174) can now be simplified quite nicely. Wouldn't be surprised if this also gives a nice performance boost to pantab.

We (i.e.: Tableau Hyper team) will see how we find time to contribute a fix for this. Expect to hear something within the next week(s). If somebody else finds time to fix this earlier, please go ahead. Happy to provide any advice/guidance/code reviews.
In the meantime, your best option is to pin Hyper API at version 0.0.14401

**Comment by Btibert3** [comment] 2022-03-25 03:37
Also just noticed this throwing install errors when using Google Colab.

**Comment by rachwng** [comment] 2022-03-25 14:53
Hi,

 pip install --force-reinstall tableauhyperapi==0.0.14401 --user
Collecting tableauhyperapi==0.0.14401
  Using cached tableauhyperapi-0.0.14401-py3-none-win_amd64.whl (34.4 MB)
Collecting cffi!=1.14.3,<2,>=1.12.2
  Using cached cffi-1.15.0-cp39-cp39-win_amd64.whl (180 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Installing collected packages: pycparser, cffi, tableauhyperapi
Successfully installed cffi-1.15.0 pycparser-2.21 tableauhyperapi-0.0.14401

But running import pantab:

---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_8824/1171623716.py in <module>
      9 import os,glob,re,sys
     10 pd.options.mode.chained_assignment=None
---> 11 import pantab
     12 from openpyxl import load_workbook
     13 from openpyxl.worksheet.datavalidation import DataValidation

~\anaconda3\lib\site-packages\pantab\__init__.py in <module>
    107         "hyper_destroy_rowset_chunk", "void(*)(struct hyper_rowset_chunk_t *)"
    108     ),
--> 109     _get_hapi_function(
    110         "hyper_rowset_chunk_field_values",
    111         "struct hyper_error_t *(*)(struct hyper_rowset_chunk_t *, size_t *, size_t *, uint8_t * * *, size_t * *, int8_t * *)",

~\anaconda3\lib\site-packages\pantab\__init__.py in _get_hapi_function(name, sig)
     56         f"expected '{name}' to be a function, got {func_type.kind}",
     57     )
---> 58     _check_compatibility(
     59         func_type.cname == sig,
     60         f"expected '{name}' to have the signature '{sig}', got '{func_type.cname}'",

~\anaconda3\lib\site-packages\pantab\__init__.py in _check_compatibility(check, message)
     45 def _check_compatibility(check, message):
     46     if not check:
---> 47         raise NotImplementedError(message + "\n" + api_incompatibility_msg)
     48 
     49 

NotImplementedError: expected 'hyper_rowset_chunk_field_values' to have the signature 'struct hyper_error_t *(*)(struct hyper_rowset_chunk_t *, size_t *, size_t *, uint8_t * * *, size_t * *, int8_t * *)', got 'void(*)(struct hyper_rowset_chunk_t *, size_t *, size_t *, uint8_t * * *, size_t * *)'

pantab is incompatible with the version of Tableau Hyper API installed on your
system. Please upgrade both `tableauhyperapi` and `pantab` to the latest version.
If doing so does not fix this issue, please file an issue at
https://github.com/innobi/pantab/issues mentioning the exact pantab and HyperAPI
versions which triggered this error.

_________________
Still facing the same issue. Please help!

**Comment by vogelsgesang** [comment] 2022-03-25 17:03
@rachwng It seems like your downgrade did not take effect as intended. I don't know anaconda, and don't know what could have gone wrong, but the error message raised by pantab still indicates that you are on a newer version of HyperAPI

**Comment by SarahBeth026** [comment] 2022-05-24 03:31
I'm getting this error also, but slightly different 
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/54331462/169942842-41fbbf08-c4a2-4547-ae8b-a6bb9b8a730b.png">
I have pantab v2.1.0 and tableauhyperapi v0.0.14751. I tried running `pip install --force-reinstall tableauhyperapi==0.0.14401 --user` and confirmed that it was using that version by running `pip show tableauhyperapi| grep Version`, but I'm still getting the same error. Any other ideas?

**Comment by WillAyd** [comment] 2022-05-24 04:41
@SarahBeth026 are you sure the environment you are running pantab from is the same as the one with the tableauhyperapi you force reinstalled? Based off of what you’ve described I think those might be getting mixed up

**Comment by WillAyd** [comment] 2022-06-27 19:55
@Carole-R looks like there are merge issues and outstanding comments on that PR. Is that something you would like to take over?

**Comment by Carole-R** [comment] 2022-06-29 15:53
@WillAyd I'm a Python beginner for now. If @vogelsgesang wasn't able to go through the update, I don't think I'll be able to do better.
I'll stick to pinning Hyper API at version 0.0.14401. Let's hope it won't slow new users from using Pantab (which is a very useful tool imo).

**Closed** 2022-09-06 18:30 UTC
