### ISSUE TITLE
Free memory after inserting data

### ISSUE THREAD

**Issue by mohamedhamnache** [innobi/pantab#268] opened 2024-02-14 14:57 UTC
Hello @WillAyd,
I am testing the pre-release of pantab 4.x  to read big csv.gz file in chunks of 1000000 lines each and insert in hyper database. The memory is increasing without being released.  Same code is run using pantab 3.0.4 and 4.x  ==> 2G of memory used for 3.0.4 and more than 9G for 4.x

**Comment by mohamedhamnache** [comment] 2024-02-14 15:21
`
chunksize = 1000000
df = pd.read_csv(
        csv_file,
        compression="gzip",
        header=None,
        names=names
        chunksize=chunksize,
    )
    for chunk in df:
        chunk = chunk.replace(np.nan, None)
        chunk = chunk.astype(types)
        pantab.frame_to_hyper(
            chunk, path_to_database, table="test", table_mode="a"
        )`

Where names are the column names and types are column dtypes.

**Comment by WillAyd** [comment] 2024-02-14 15:33
Thanks but I can't run that code as is to reproduce anything. Can you try to produce something minimal to help isolate the issue? Is it certain data types that cause the leak or anything? And how are you measuring what is being leaked?

**Comment by mohamedhamnache** [comment] 2024-02-14 15:42
I am running my code with both pantab versions mentioned above, and I opened htop to monitor the memory usage by the process. For the 3.0.4 version, I can see that memory is released after each iteration of the for loop (memory usage is stable around 2G). When I run the same code using 4.x, memory usage increases after each loop iteration (increased from 2G to 9G).
Not related to certain data types

**Comment by WillAyd** [comment] 2024-02-14 22:36
@mohamedhamnache I think this should be fixed now. Can you install from github and check?

I do still see _some_ leaks when checking the process monitor but I _think_ those are coming from the Hyper process itself which we can't control. Hoping the PR above fixed the bigger issues here

**Comment by WillAyd** [comment] 2024-02-15 03:27
Actually I think the issue still exists, but it isn't directly caused by pantab. If you use pyarrow Tables directly I do not see any memory growth. Here is an MRE:

```python
import numpy as np
import pyarrow as pa
import pantab as pt


arr = pa.array(np.random.randn(100_000))
tbl = pa.Table.from_arrays([arr] * 10, names=list("abcdefghij"))
while True:
    pt.frame_to_hyper(tbl, "example.hyper", table="table", table_mode="a")
```

I cannot get a leak with that directly. So the leak seems to be something with pandas and how it converts to pyarrow

**Comment by WillAyd** [comment] 2024-02-15 04:10
OK I think finally fixed now. Try again and let me know if you see the same results - thanks!

**Closed** 2024-02-15 04:09 UTC
