### ISSUE TITLE
Getting Segmentation fault when writing dataframe to hyper file in Docker python3.8-slim

### ISSUE THREAD

**Issue by zarlant** [innobi/pantab#99] opened 2020-05-04 18:19 UTC
When running the function:
```python
pantab.frame_to_hyper(self.data_frame, file_name, table=table_name)
```

```
Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
hyperapi::InserterBuffer::addInt64 (this=0x55a67711dce0, value=<optimized out>) at ./api/cxx/hyperapi-c/hyperapi/api/InserterBuffer.hpp:102
102	./api/cxx/hyperapi-c/hyperapi/api/InserterBuffer.hpp: No such file or directory.
```

**To Reproduce**
In a Docker image 

FROM python3.8-slim
RUN pip install tableauhyperapi==0.0.10309 pantab==1.0.1

Build a dataframe with an int64 column type
Run pantab.frame_to_hyper function

**Expected behavior**
Hyper file successfully built

**Desktop (please complete the following information):**
 - OS: Docker python3.8-slim

**Additional context**
It looks like this error is specific to having a different version of either pantab / tableauhyperapi than their respective releases were built with.

Seems like a simple fix in pantab would be to specify hard requirements for the tableauhyperapi version that is supported.

**Comment by WillAyd** [comment] 2020-05-04 18:23
Can you upgrade to 1.1? The newest released version should address some segfaults

**Comment by zarlant** [comment] 2020-05-04 19:13
When I upgrade to 1.1 with the same version of tableauhyperapi I get the following segfault:

```bash
Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
__GI___libc_free (mem=0x175af4144c639ee2) at malloc.c:3093
3093	malloc.c: No such file or directory.
```

If I upgrade to tableauhyperapi==0.0.10622 then things work fine, so that's why I was wondering if you could just update the setup.py to include a version tag that is needed for the hyperapi dependency.

Or maybe this is just a separate bug in pantab, and there isn't that tight of a coupling normally.

As far as troubleshooting goes, is there a way to bubble up this exception to the python interpreter itself? (I had to enlist the help of the hyper api dev team to figure out this issue)

**Comment by WillAyd** [comment] 2020-05-05 01:03
Can you point me to where that Dockerfile comes from? Curious to see what environment it uses as I can't reproduce on a Mac.



> If I upgrade to tableauhyperapi==0.0.10622 then things work fine, so that's why I was wondering if you could just update the setup.py to include a version tag that is needed for the hyperapi dependency.

Might be something I don't know, but if this is a reference to `install_requires` setuptools advises against doing that. I also don't think really solves the issue as users can subsequently still upgrade the tableau hyper api directly or indirectly through other packages



> As far as troubleshooting goes, is there a way to bubble up this exception to the python interpreter itself? (I had to enlist the help of the hyper api dev team to figure out this issue)

Unfortunately not. A segfault is a fatal program error so nothing something the Python interpreter catches

**Comment by WillAyd** [comment] 2020-10-22 15:48
@zarlant is this still an issue?

**Comment by WillAyd** [comment] 2021-02-16 16:34
Closing for lack of info and age. Please reply back if still an issue

**Closed by WillAyd** 2021-02-16 16:34 UTC
